openapi: 3.0.0
info:
  title: Cars API
  version: '1.0'
servers:
  - url: http://localhost:5000/api
paths:
  /cars:
    get:
      summary: Get all cars
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
    post:
      summary: Add new car
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
  /cars/{id}:
    get:
      summary: Get car by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the car to get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
    put:
      summary: Update car by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the car to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
    delete:
      summary: Delete car by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the car to delete
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Car:
      type: object
      properties:
        id:
          type: integer
          format: int64
        full_name:
          type: string
        mark:
          type: string
        semester:
          type: integer
          format: int32
        mark:
          type: integer
          format: int32
        year_of_study:
          type: integer
          format: int32
        age:
          type: integer
          format: int32
      required:
        - full_name
        - mark
        - semester
        - mark
        - year_of_study
        - age
